apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: default
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    directory:
      recurse: true
    path: envs/default
  destination:
    server: https://kubernetes.default.svc
    namespace: default